[package]
name = "opengl-learning"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.25.0", features = ["derive"] }
env_logger = "0.11.10"
glam = { version = "0.33.1", features = ["bytemuck"] }
glow = "0.17.0"
glutin = { version = "0.32.3", features = ["egl", "glx", "wayland"] }
glutin-winit = "0.5.0"
log = "0.4.32"
raw-window-handle = "0.6.2"
winit = "0.30.13"
