[package]
    edition.workspace=true
    license.workspace=true
    name="rendering-engine"
    version.workspace=true

[lib]
    crate-type=["rlib"]

[dependencies]
    anyhow.workspace=true
    bytemuck.workspace=true
    glam.workspace=true
    glow.workspace=true
    include_dir.workspace=true
    log.workspace=true

    [package.metadata.android.signing.release]
        key_alias="upload"
        key_password="@env:ANDROID_KEY_PASSWORD"
        keystore_password="@env:ANDROID_KEYSTORE_PASSWORD"
        path="../keys/upload-keystore.jks"
