[package]
    edition.workspace=true
    license.workspace=true
    name="rendering-engine"
    version.workspace=true

[lib]
    crate-type=["rlib"]

[dependencies]
    anyhow.workspace=true
    bytemuck.workspace=true
    glam.workspace=true
    glow.workspace=true
    include_dir.workspace=true
    log.workspace=true
