[package]
    edition="2024"
    name="desktop-demo"
    version="0.1.0"

[dependencies]
    anyhow="1.0.104"
    bytemuck={version="1.25.2", features=["derive"]}
    env_logger="0.11.11"
    glam={version="0.33.2", features=["bytemuck"]}
    glow="0.18.0"
    glutin="0.32.3"
    glutin-winit="0.5.0"
    include_dir="0.7.4"
    log="0.4.33"
    raw-window-handle="0.6.2"
    rendering-engine={path="../engine"}
    winit={version="0.30.13"}
