name: Android APK Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            ANDROID_NDK_VERSION: 26.3.11579264

        steps:
            - uses: actions/checkout@v7

            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: |
                      aarch64-linux-android
                      armv7-linux-androideabi

            - uses: android-actions/setup-android@v4

            - name: Install NDK
              run: sdkmanager "ndk;$ANDROID_NDK_VERSION"

            - name: Set NDK path
              run: |
                  echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV
                  echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV

            - name: Install cargo-apk
              run: cargo install cargo-apk

            - name: Build APK
              run: cargo apk build -p demo --lib

            - name: Upload APK
              uses: actions/upload-artifact@v7
              with:
                  name: demo
                  path: |
                      target/debug/apk/*.apk
                      target/release/apk/*.apk
